version: "3.9"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - 45432:5432
    volumes:
      - dbdata:/var/lib/postgresql/finance/data

  api:
    build: .
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/financedb?schema=public
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - postgres
    healthcheck:
      test: psql -U $POSTGRES_USER $POSTGRES_DB || exit 1
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 5m

volumes:
  dbdata:
